const platforms={tiktok:{role:"Discovery · creator education",title:"Lead with texture, not a claim.",format:"9:16 · 12–18 seconds",opening:"Macro texture in the first second",signal:"3-second hold · completion"},instagram:{role:"Consideration · saveable education",title:"Make one product purpose feel memorable.",format:"4:5 carousel · 9:16 Reel",opening:"One product, one purpose",signal:"Save rate · detail clicks"},pinterest:{role:"Evergreen · search-led discovery",title:"Design a routine people can return to.",format:"2:3 vertical pin",opening:"Morning / night routine context",signal:"Saves · outbound clicks"},amazon:{role:"Commerce · product comprehension",title:"Resolve the last practical questions.",format:"1:1 image sequence",opening:"Packshot and verified feature hierarchy",signal:"Detail engagement · add to cart"}};
function renderPlatform(key){const item=platforms[key];document.querySelector("#platform-role").textContent=item.role;document.querySelector("#platform-title").textContent=item.title;document.querySelector("#platform-format").textContent=item.format;document.querySelector("#platform-opening").textContent=item.opening;document.querySelector("#platform-signal").textContent=item.signal;document.querySelectorAll("[data-platform]").forEach(button=>button.classList.toggle("active",button.dataset.platform===key));}
document.querySelectorAll("[data-platform]").forEach(button=>button.addEventListener("click",()=>renderPlatform(button.dataset.platform)));renderPlatform("tiktok");

const prompts=[
 {id:"IP—01",name:"Texture Truth",ratio:"9:16",text:"Premium editorial skincare macro photograph, a single translucent watery serum droplet forming at the tip of a clear glass dropper above a warm ivory surface, physically plausible viscosity, soft directional morning daylight, subtle sage reflection, crisp micro-detail, restrained luxury, generous upper-left negative space for later typography, no label, no logo, no skin, no medical diagram, no text, photorealistic product photography.",negative:"brand logo, readable text, clinical cross-section, glowing particles, skin penetration, miracle effect, excessive sparkle, thick gel, impossible reflections, distorted glass, watermark"},
 {id:"IP—02",name:"Routine Placement",ratio:"4:5",text:"Clean editorial bathroom shelf in soft natural daylight, four clearly separated neutral skincare objects arranged left to right as cleanser, unlabeled serum dropper bottle, moisturizer jar, sunscreen tube, warm ivory stone and pale sage accents, simple three-step visual rhythm, realistic scale and shadows, right-side negative space for numbered labels added later, no logos, no embedded words, photorealistic commercial still life.",negative:"brand packaging, readable labels, medical symbols, prescription products, clutter, impossible shadows, warped containers, floating objects, watermark"},
 {id:"IP—03",name:"Creator Countertop",ratio:"9:16",text:"Authentic creator-style vertical beauty scene, adult hand with natural unretouched skin holding a generic unlabeled serum bottle beside a bathroom mirror, soft morning window light, warm neutral and pale sage palette, subtle handheld framing, visible real skin texture, one controlled droplet on fingertip, lower-third safe space for captions, calm educational mood, no brand identity, no before-and-after comparison.",negative:"celebrity likeness, child, flawless plastic skin, skin lightening, acne removal, split-screen transformation, testimonial text, logo, extra fingers, deformed hand, watermark"},
 {id:"IP—04",name:"Commerce Clarity",ratio:"1:1",text:"High-end e-commerce skincare still life, centered generic frosted glass serum bottle with blank label on a warm ivory matte surface, restrained translucent ingredient-inspired abstract shapes in the background, soft controlled studio daylight, accurate straight bottle geometry, clean charcoal-shadow contrast, ample empty space for verified feature callouts added later, photorealistic, conversion-focused composition without promotional claims.",negative:"real logo, readable text, certification badge, molecule diagram, medical imagery, competitor packaging, sale sticker, glowing aura, impossible bottle, duplicate caps, warped label, watermark"}
];
const list=document.querySelector("#prompt-list");list.innerHTML=prompts.map((prompt,index)=>`<article class="prompt-item ${index===0?"open":""}"><button class="prompt-head" aria-expanded="${index===0}"><span>${prompt.id}</span><strong>${prompt.name}</strong><i>+</i></button><div class="prompt-body"><div class="prompt-meta"><span>ASPECT ${prompt.ratio}</span><span>STATUS · CONCEPT ONLY</span></div><pre>${prompt.text}\n\nAVOID: ${prompt.negative}</pre><button class="copy-button" data-copy>Copy prompt</button></div></article>`).join("");
list.addEventListener("click",async event=>{const head=event.target.closest(".prompt-head");if(head){const item=head.closest(".prompt-item");item.classList.toggle("open");head.setAttribute("aria-expanded",item.classList.contains("open"));}const copy=event.target.closest("[data-copy]");if(copy){const text=copy.previousElementSibling.textContent;await navigator.clipboard.writeText(text);copy.textContent="Copied";setTimeout(()=>copy.textContent="Copy prompt",1400);}});
